---
# CiliumBGPClusterConfig for BGP peering with FRR container
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-config
spec:
  nodeSelector:
    matchLabels:
      bgp: "enabled"
  bgpInstances:
  - name: "instance-4200099999"
    localASN: 4200099999
    peers:
    - name: "frr-container"
      peerASN: 4200099998
      peerAddress: "192.168.250.254"
      peerConfigRef:
        name: "frr-peer-config"
---
# CiliumBGPPeerConfig for FRR peering parameters
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: frr-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
  - afi: ipv6
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
---
# CiliumBGPAdvertisement for LoadBalancer services
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: loadbalancer-services
  labels:
    advertise: "bgp"
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
      selector:
        matchExpressions:
        - key: "service.kubernetes.io/service-proxy-name"
          operator: "NotIn"
          values: ["kube-proxy"]
---
# CiliumBGPAdvertisement for PodCIDR (optional)
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr
  labels:
    advertise: "bgp"
spec:
  advertisements:
  - advertisementType: "PodCIDR"
    attributes:
      communities:
        standard: ["65000:100"]